name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  release:
    uses: matter-labs/zksync-ci-common/.github/workflows/release-please.yaml@aba-add-all-outputs
    secrets:
      gh_token: ${{ secrets.RELEASE_TOKEN }}
      cargo_registry_token: ${{ secrets.CRATES_IO_TOKEN }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
    with:
      manifest: '.github/release-please/manifest.json' # Specify the path to the manifest file
      config: '.github/release-please/config.json'     # Specify the path to the configuration file
      org-owner: 'antonbaliasnikov'                    # Specify the organization owner if you want update ownership of the crates
      update-cargo-lock: false                         # Update Cargo.lock file
      workspace-dirs: 'core prover zkstack'            # Workspace directories to update Cargo.lock
      publish-to-crates-io: false                      # Enable publishing to crates.io
      upgrade-dependencies: false                      # Upgrade workspace dependencies
      version-suffix: 'not-semver-compat'              # Specify the version suffix for the crates

  check:
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Check
        run: |
          echo "${{ needs.release-please.outputs.all['zkstack--release_created'] }}"

  release-zkstack-cli-bins:
    if: ${{ needs.release-please.outputs.all['zkstack--release_created'] == 'true' }}
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "tag = ${{ needs.release-please.outputs.all['zkstack--tag_name'] }}"
